export type TransitMode = "flight" | "train" | "bus" | "car" | "unknown";

export type TransitLink = {
  mode: TransitMode;
  origin: string;
  destination: string;
  estimatedDurationMinutes: number;
  isApproximate: boolean; // true = generated by generic routing provider, false = real booked travel segment
};

export class ApproximateRoutingProvider {
  /**
   * Generates approximate transit links between a sequence of locations.
   */
  static getRoute(waypoints: string[]): TransitLink[] {
    const links: TransitLink[] = [];
    
    for (let i = 0; i < waypoints.length - 1; i++) {
      const origin = waypoints[i];
      const destination = waypoints[i + 1];
      
      // Extremely basic logic for now. 
      // If we had coordinates, we could estimate distance and determine mode (flight vs train/bus/car)
      // Here we just mock it.
      
      let mode: TransitMode = "car";
      let estimatedDurationMinutes = 120; // 2 hours

      // Very simple hardcoded heuristic for some well-known paths
      const pair = `${origin.toLowerCase()}-${destination.toLowerCase()}`;
      
      if (pair.includes("delhi") && (pair.includes("mumbai") || pair.includes("bangalore"))) {
        mode = "flight";
        estimatedDurationMinutes = 150;
      } else if (pair.includes("srinagar") && pair.includes("gulmarg")) {
        mode = "car";
        estimatedDurationMinutes = 90;
      }
      
      links.push({
        mode,
        origin,
        destination,
        estimatedDurationMinutes,
        isApproximate: true,
      });
    }
    
    return links;
  }
}
